version: "3.7"
services:
  db:
    image: "satelit/import-db:12-alpine"
    volumes:
      - type: "bind"
        source: "/mnt/satelit_import/pgdata"
        target: "/var/lib/postgresql/data/pgdata"
    logging:
      driver: "journald"
    networks:
      - "backend"
    expose:
      - 5432

  indexer:
    image: "satelit/satelit-index:0.1"
    depends_on:
      - db
    env_file: .env
    environment:
      - "PG_DB_URL=postgresql://postgres@db/satelit_index?sslmode=disable"
    logging:
      driver: "journald"
    networks:
      - "backend"
    expose:
      - 8080

networks:
  backend:
